In [1]:
import pandas as pd

import sys 
sys.path.append("..")

# Importing the Keras libraries and packages for LSTM
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LSTM

import tensorflow as tf

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split

import numpy as np

# Feature Scaling
from sklearn.preprocessing import MinMaxScaler

2022-05-03 17:41:15.038841: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-05-03 17:41:15.038929: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

In [2]:
import os
from dotenv import load_dotenv
import pandas as pd

secrets_path = os.path.join(os.getenv("PWD"), ".secrets")
load_dotenv(override=True)
load_dotenv(secrets_path, override=True)

True

In [3]:
df_train_1 = pd.read_csv("../data/raw/train_1.csv.zip", compression="zip")

In [4]:
df_key_1 = pd.read_csv("../data/raw/key_1.csv.zip", compression="zip")

In [5]:
df_train_1.describe()

,2015-07-01,2015-07-02,2015-07-03,2015-07-04,2015-07-05,2015-07-06,2015-07-07,2015-07-08,2015-07-09,2015-07-10,...,2016-12-22,2016-12-23,2016-12-24,2016-12-25,2016-12-26,2016-12-27,2016-12-28,2016-12-29,2016-12-30,2016-12-31
count,1.243230e+05,1.242470e+05,1.245190e+05,1.244090e+05,1.244040e+05,1.245800e+05,1.243990e+05,1.247690e+05,1.248190e+05,1.247210e+05,...,1.412100e+05,1.414790e+05,1.418740e+05,1.413190e+05,1.411450e+05,1.413620e+05,1.412410e+05,1.412370e+05,1.414280e+05,1.415980e+05
mean,1.195857e+03,1.204004e+03,1.133676e+03,1.170437e+03,1.217769e+03,1.290273e+03,1.239137e+03,1.193092e+03,1.197992e+03,1.189651e+03,...,1.394096e+03,1.377482e+03,1.393099e+03,1.523740e+03,1.679607e+03,1.678302e+03,1.633966e+03,1.684308e+03,1.467943e+03,1.478282e+03
std,7.275352e+04,7.421515e+04,6.961022e+04,7.257351e+04,7.379612e+04,8.054448e+04,7.576288e+04,6.820002e+04,7.149717e+04,7.214536e+04,...,8.574880e+04,7.732794e+04,8.478533e+04,8.752210e+04,9.794534e+04,9.232482e+04,9.185831e+04,9.014266e+04,8.155481e+04,8.873567e+04
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.300000e+01,1.300000e+01,1.200000e+01,1.300000e+01,1.400000e+01,1.100000e+01,1.300000e+01,1.300000e+01,1.400000e+01,1.400000e+01,...,2.200000e+01,2.200000e+01,2.000000e+01,2.100000e+01,2.200000e+01,2.300000e+01,2.400000e+01,2.300000e+01,2.300000e+01,2.100000e+01
50%,1.090000e+02,1.080000e+02,1.050000e+02,1.050000e+02,1.130000e+02,1.130000e+02,1.150000e+02,1.170000e+02,1.150000e+02,1.130000e+02,...,1.490000e+02,1.430000e+02,1.320000e+02,1.450000e+02,1.600000e+02,1.620000e+02,1.630000e+02,1.600000e+02,1.540000e+02,1.360000e+02
75%,5.240000e+02,5.190000e+02,5.040000e+02,4.870000e+02,5.400000e+02,5.550000e+02,5.510000e+02,5.540000e+02,5.490000e+02,5.450000e+02,...,6.070000e+02,5.980000e+02,5.690000e+02,6.280000e+02,6.590000e+02,6.680000e+02,6.540000e+02,6.490000e+02,6.350000e+02,5.610000e+02
max,2.038124e+07,2.075219e+07,1.957397e+07,2.043964e+07,2.077211e+07,2.254467e+07,2.121089e+07,1.910791e+07,1.999385e+07,2.020182e+07,...,2.420108e+07,2.253925e+07,2.505662e+07,2.586575e+07,2.834288e+07,2.691699e+07,2.702505e+07,2.607382e+07,2.436397e+07,2.614954e+07

In [6]:
df_train_1.head()

,Page,2015-07-01,2015-07-02,2015-07-03,2015-07-04,2015-07-05,2015-07-06,2015-07-07,2015-07-08,2015-07-09,...,2016-12-22,2016-12-23,2016-12-24,2016-12-25,2016-12-26,2016-12-27,2016-12-28,2016-12-29,2016-12-30,2016-12-31
0,2NE1_zh.wikipedia.org_all-access_spider,18.0,11.0,5.0,13.0,14.0,9.0,9.0,22.0,26.0,...,32.0,63.0,15.0,26.0,14.0,20.0,22.0,19.0,18.0,20.0
1,2PM_zh.wikipedia.org_all-access_spider,11.0,14.0,15.0,18.0,11.0,13.0,22.0,11.0,10.0,...,17.0,42.0,28.0,15.0,9.0,30.0,52.0,45.0,26.0,20.0
2,3C_zh.wikipedia.org_all-access_spider,1.0,0.0,1.0,1.0,0.0,4.0,0.0,3.0,4.0,...,3.0,1.0,1.0,7.0,4.0,4.0,6.0,3.0,4.0,17.0
3,4minute_zh.wikipedia.org_all-access_spider,35.0,13.0,10.0,94.0,4.0,26.0,14.0,9.0,11.0,...,32.0,10.0,26.0,27.0,16.0,11.0,17.0,19.0,10.0,11.0
4,52_Hz_I_Love_You_zh.wikipedia.org_all-access_s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,48.0,9.0,25.0,13.0,3.0,11.0,27.0,13.0,36.0,10.0

In [7]:
df_key_1

                                                      Page            Id
0        !vote_en.wikipedia.org_all-access_all-agents_2...  bf4edcf969af
1        !vote_en.wikipedia.org_all-access_all-agents_2...  929ed2bf52b9
2        !vote_en.wikipedia.org_all-access_all-agents_2...  ff29d0f51d5c
3        !vote_en.wikipedia.org_all-access_all-agents_2...  e98873359be6
4        !vote_en.wikipedia.org_all-access_all-agents_2...  fa012434263a
...                                                    ...           ...
8703775  龙生九子_zh.wikipedia.org_mobile-web_all-agents_20...  f69747f5ee68
8703776  龙生九子_zh.wikipedia.org_mobile-web_all-agents_20...  2489963dc503
8703777  龙生九子_zh.wikipedia.org_mobile-web_all-agents_20...  b0624c909f4c
8703778  龙生九子_zh.wikipedia.org_mobile-web_all-agents_20...  24a1dfb06c10
8703779  龙生九子_zh.wikipedia.org_mobile-web_all-agents_20...  add681d54216

[8703780 rows x 2 columns]

In [8]:
df_train_1

,Page,2015-07-01,2015-07-02,2015-07-03,2015-07-04,2015-07-05,2015-07-06,2015-07-07,2015-07-08,2015-07-09,...,2016-12-22,2016-12-23,2016-12-24,2016-12-25,2016-12-26,2016-12-27,2016-12-28,2016-12-29,2016-12-30,2016-12-31
0,2NE1_zh.wikipedia.org_all-access_spider,18.0,11.0,5.0,13.0,14.0,9.0,9.0,22.0,26.0,...,32.0,63.0,15.0,26.0,14.0,20.0,22.0,19.0,18.0,20.0
1,2PM_zh.wikipedia.org_all-access_spider,11.0,14.0,15.0,18.0,11.0,13.0,22.0,11.0,10.0,...,17.0,42.0,28.0,15.0,9.0,30.0,52.0,45.0,26.0,20.0
2,3C_zh.wikipedia.org_all-access_spider,1.0,0.0,1.0,1.0,0.0,4.0,0.0,3.0,4.0,...,3.0,1.0,1.0,7.0,4.0,4.0,6.0,3.0,4.0,17.0
3,4minute_zh.wikipedia.org_all-access_spider,35.0,13.0,10.0,94.0,4.0,26.0,14.0,9.0,11.0,...,32.0,10.0,26.0,27.0,16.0,11.0,17.0,19.0,10.0,11.0
4,52_Hz_I_Love_You_zh.wikipedia.org_all-access_s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,48.0,9.0,25.0,13.0,3.0,11.0,27.0,13.0,36.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145058,Underworld_(serie_de_películas)_es.wikipedia.o...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,13.0,12.0,13.0,3.0,5.0,10.0
145059,Resident_Evil:_Capítulo_Final_es.wikipedia.org...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145060,Enamorándome_de_Ramón_es.wikipedia.org_all-acc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145061,Hasta_el_último_hombre_es.wikipedia.org_all-ac...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145062,Francisco_el_matemático_(serie_de_televisión_d...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
#Dropping Page Column
df_train_1 = df_train_1.drop('Page',axis = 1)

In [10]:
df_train_1 = df_train_1.fillna(0)

In [11]:
len(df_train_1.columns)

550

In [12]:
df_train, df_test = train_test_split(df_train_1, test_size = 0.3, random_state = 0)

In [13]:
df_train

,2015-07-01,2015-07-02,2015-07-03,2015-07-04,2015-07-05,2015-07-06,2015-07-07,2015-07-08,2015-07-09,2015-07-10,...,2016-12-22,2016-12-23,2016-12-24,2016-12-25,2016-12-26,2016-12-27,2016-12-28,2016-12-29,2016-12-30,2016-12-31
115573,219.0,188.0,206.0,245.0,294.0,181.0,160.0,194.0,210.0,189.0,...,275.0,388.0,911.0,40997.0,5017.0,4809.0,4534.0,1464.0,701.0,505.0
119236,1375.0,1373.0,1251.0,1568.0,1363.0,1134.0,1100.0,1001.0,935.0,980.0,...,1250.0,1156.0,868.0,865.0,1810.0,1664.0,1679.0,1732.0,1301.0,18825.0
66613,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
57569,53.0,49.0,58.0,62.0,75.0,134.0,70.0,72.0,49.0,89.0,...,559.0,596.0,2805.0,898.0,509.0,465.0,397.0,601.0,1045.0,2357.0
84607,2.0,11.0,8.0,11.0,18.0,11.0,13.0,5.0,0.0,5.0,...,17.0,22.0,16.0,19.0,9.0,10.0,10.0,10.0,15.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41993,154.0,151.0,139.0,106.0,99.0,135.0,124.0,116.0,127.0,126.0,...,2328.0,1125.0,522.0,571.0,695.0,766.0,584.0,531.0,456.0,508.0
97639,0.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,2.0,1.0,...,0.0,2.0,0.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0
95939,317.0,336.0,351.0,382.0,479.0,413.0,402.0,355.0,362.0,314.0,...,553.0,523.0,634.0,638.0,725.0,595.0,598.0,1732.0,709.0,555.0
117952,20.0,24.0,20.0,16.0,29.0,57.0,28.0,40.0,25.0,30.0,...,20.0,19.0,25.0,21.0,14.0,27.0,18.0,16.0,26.0,7.0
43567,12.0,17.0,19.0,8.0,11.0,16.0,22.0,12.0,20.0,20.0,...,10.0,18.0,7.0,6.0,13.0,12.0,21.0,23.0,14.0,11.0

In [14]:
#Using Data From Random Row for Training and Testing
sc = MinMaxScaler()

df_train_scaled = sc.fit_transform(df_train)
df_test_scaled = sc.transform(df_test)

In [15]:
x_train = df_train_scaled[:, :-1]
y_train = df_train_scaled[:, -1]

In [16]:
x_test = df_test_scaled[:, :-1]
y_test = df_test_scaled[:, -1]

In [17]:
import tensorflow.keras.backend as K

def smape_loss(y_true, y_pred):
    epsilon = 0.001
    summ = K.maximum(K.abs(y_true) + K.abs(y_pred) + epsilon, 0.5 + epsilon)
    smape = K.abs(y_pred - y_true) / summ * 2.0
    return smape

# SMAPE as Kaggle calculates it
def kaggle_smape(true, predicted):
    true_o = true
    pred_o = predicted
    summ = K.abs(true_o) + K.abs(pred_o) + 0.000001
    smape = np.where(summ==0, 0, K.abs(pred_o - true_o) / summ)
    return smape

In [26]:
# Initialising the RNN
regressor = Sequential()

# Adding the input layerand the LSTM layer
regressor.add(LSTM(units = 8, activation = 'relu', input_shape = (None, 1)))

# Adding the output layer
regressor.add(Dense(units = 1))

# Compiling the RNN
regressor.compile(optimizer = 'adam', loss = smape_loss)

# Fitting the RNN to the Training set
regressor.fit(x_train, y_train, batch_size = 512, epochs = 10, verbose = 1, validation_split=0.1)

Epoch 1/10
179/179 [==============================] - 58s 322ms/step - loss: 5.8604e-04 - val_loss: 1.7156e-04
Epoch 2/10
179/179 [==============================] - 81s 455ms/step - loss: 4.9708e-04 - val_loss: 7.6815e-04
Epoch 3/10
179/179 [==============================] - 77s 429ms/step - loss: 6.2791e-04 - val_loss: 7.1858e-04
Epoch 4/10
179/179 [==============================] - 88s 490ms/step - loss: 5.7535e-04 - val_loss: 8.9640e-04
Epoch 5/10
179/179 [==============================] - 98s 546ms/step - loss: 6.1695e-04 - val_loss: 2.3781e-04
Epoch 6/10
179/179 [==============================] - 98s 546ms/step - loss: 4.6474e-04 - val_loss: 7.0155e-04
Epoch 7/10
179/179 [==============================] - 102s 567ms/step - loss: 6.4048e-04 - val_loss: 4.4298e-04
Epoch 8/10
179/179 [==============================] - 109s 609ms/step - loss: 5.6075e-04 - val_loss: 3.7690e-04
Epoch 9/10
179/179 [==============================] - 107s 597ms/step - loss: 5.1573e-04 - val_loss: 5.5757e-04
Epoch 10/10
179/179 [==============================] - 103s 574ms/step - loss: 8.4621e-04 - val_loss: 5.4506e-04

In [19]:
## Darts

In [22]:
import pandas as pd
import numpy as np
from tqdm import tqdm
import datetime
import random

from sklearn.base import TransformerMixin
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.preprocessing import FunctionTransformer
from sklearn.impute import SimpleImputer

import joblib
import pickle
import os

from darts import TimeSeries
from darts.metrics import mape, smape
from darts.models import RNNModel, NBEATSModel

from torch.nn import L1Loss
import torch
import torch.optim as optim

In [23]:
import darts

In [25]:
df_train_1

,2015-07-01,2015-07-02,2015-07-03,2015-07-04,2015-07-05,2015-07-06,2015-07-07,2015-07-08,2015-07-09,2015-07-10,...,2016-12-22,2016-12-23,2016-12-24,2016-12-25,2016-12-26,2016-12-27,2016-12-28,2016-12-29,2016-12-30,2016-12-31
0,18.0,11.0,5.0,13.0,14.0,9.0,9.0,22.0,26.0,24.0,...,32.0,63.0,15.0,26.0,14.0,20.0,22.0,19.0,18.0,20.0
1,11.0,14.0,15.0,18.0,11.0,13.0,22.0,11.0,10.0,4.0,...,17.0,42.0,28.0,15.0,9.0,30.0,52.0,45.0,26.0,20.0
2,1.0,0.0,1.0,1.0,0.0,4.0,0.0,3.0,4.0,4.0,...,3.0,1.0,1.0,7.0,4.0,4.0,6.0,3.0,4.0,17.0
3,35.0,13.0,10.0,94.0,4.0,26.0,14.0,9.0,11.0,16.0,...,32.0,10.0,26.0,27.0,16.0,11.0,17.0,19.0,10.0,11.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,48.0,9.0,25.0,13.0,3.0,11.0,27.0,13.0,36.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145058,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,13.0,12.0,13.0,3.0,5.0,10.0
145059,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
145060,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
145061,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
145062,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
TimeSeries.from_dataframe(

)